name: Test S3 Upload
on:
  workflow_dispatch: {}
jobs:
  testS3Upload:
    name: Test s3 Upload
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
         
      - name: Copy Template to Dev
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://studiogarnish-demos/chimera/template
          destination: s3://studiogarnish-demos/chimera/dev
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          flags: --recursive --acl bucket-owner-full-control --acl public-read
      
